---
- name: Check URL
  hosts: localhost
  connection: local
  vars:
    node: "web"

  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: "http://{{ node }}"
